"""Shared constant values for ML, trading, and UI defaults."""

LOOKBACK = 48
STEP = 1
SCALER_WINDOW = 226
TRAIN_RATIO = 0.8

ADX_WINDOW = 14
MFI_WINDOW = 14
MFI_DEFAULT_VALUE = 50
RSI_WINDOW = 14
SMA_SHORT_WINDOW = 10
SMA_LONG_WINDOW = 20
CCI_WINDOW = 20
CLOSE_POSITION_EPSILON = 1e-8
FEATURE_COLUMNS = [
    "Open",
    "High",
    "Low",
    "Close",
    "ADX",
    "ADX_pos",
    "ADX_neg",
    "MFI",
    "RSI",
    "SMA_10",
    "SMA_20",
    "CCI",
    "Price_Change",
    "HL_Range",
    "Close_Position",
]

LSTM_UNITS = (128, 64)
DENSE_UNITS = 32
DROPOUT_RATE = 0.3
LEARNING_RATE = 0.001
N_FEATURES = 15
PREDICTION_THRESHOLD = 0.5

EPOCHS = 100
BATCH_SIZE = 256
EARLY_STOPPING_PATIENCE = 30
REDUCE_LR_FACTOR = 0.5
REDUCE_LR_PATIENCE = 15
REDUCE_LR_MIN = 1e-6

DEFAULT_SYMBOL = "XAUUSD"
ALTERNATIVE_SYMBOLS = ["XAUUSDm", "GOLD", "XAUUSD.a", "XAUUSD_i"]
DEFAULT_LOT = 0.03
DEFAULT_SL_PIPS = 500
DEFAULT_TP_PIPS = 500
MAX_POSITIONS = 3
MIN_CONFIDENCE = 0.5
MAGIC_NUMBER = 12345
ORDER_DEVIATION = 20
PIP_MULTIPLIER = 10
XAUUSD_POINT = 0.01

MODEL_MODE_DUAL = "dual"
MODEL_MODE_SINGLE_M5 = "single_m5"
DEFAULT_MODEL_MODE = MODEL_MODE_DUAL
 
DEFAULT_TRAILING_SL_LEVELS = [
    (100, 5),
    (200, 100),
    (300, 200),
    (400, 300),
]
TRAILING_CHECK_INTERVAL = 1
BACKTEST_INITIAL_EQUITY = 10000.0
BACKTEST_PROFIT_MULTIPLIER = 10

CRAWL_DEFAULT_LOOKBACK_DAYS = 180

TRADE_LOG_MAX_MESSAGES = 50
REALTIME_DATA_COUNT = 350
MAX_TRADE_LOG_DISPLAY = 10
AUTO_TRADE_INTERVAL = 0.5
UI_REFRESH_INTERVAL = 3

#APP version
MODELS_DIR = "models"
ARTIFACTS_DIR = "artifacts"
DATA_DIR = "data"
LOGS_DIR = "logs"
APP_NAME = "autotrader"
APP_VERSION = "0.1.0"
API_PREFIX = "/api/v1"
